name: Build & Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write      # required to get OIDC token
      contents: read       # needed to checkout code

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::293088445135:role/github-ecs-deploy-role
        aws-region: ap-south-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password \
            --region ap-south-1 | docker login \
            --username AWS \
            --password-stdin 293088445135.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build Docker Image
      run: docker build -t 293088445135.dkr.ecr.ap-south-1.amazonaws.com/ecs-app-repo:latest .

    - name: Push to ECR
      run: docker push 293088445135.dkr.ecr.ap-south-1.amazonaws.com/ecs-app-repo:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service \
          --cluster ecs-cluster-mumbai \
          --service app-service \
          --force-new-deployment
