name: Deploy App to ECS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ap-south-1
      ECR_REPO: 293088445135.dkr.ecr.ap-south-1.amazonaws.com/ecs-oidc-demo
      ECS_CLUSTER: ecs-oidc-cluster
      ECS_SERVICE: ecs-oidc-service

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ECR_REPO

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $ECR_REPO:$IMAGE_TAG .
          docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:latest

      - name: Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker push $ECR_REPO:$IMAGE_TAG
          docker push $ECR_REPO:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment

      - name: Get ECS Task Public IP
        id: task_ip
        run: |
          TASK_ARN=$(aws ecs list-tasks \
            --cluster ${{ env.ECS_CLUSTER }} \
            --query 'taskArns[0]' --output text)
          PUBLIC_IP=$(aws ecs describe-tasks \
            --cluster ${{ env.ECS_CLUSTER }} \
            --tasks $TASK_ARN \
            --query 'tasks[0].attachments[0].details[?name==`publicIPv4Address`].value' \
            --output text)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Set app URL as output
        id: set_app_url
        run: echo "app_url=http://$PUBLIC_IP:8000" >> $GITHUB_OUTPUT

      - name: Print app URL
        run: |
          echo "App URL: ${{ steps.set_app_url.outputs.app_url }}"
